### ISSUE TITLE
"Undefined index: store" when accessing Carpenter->config

### ISSUE THREAD

**Issue by PiotrJander** [michaeljennings/carpenter#6]
When I do

``` php
Carpenter::add('manufacturers signups', ManufacturerSignupsTable::class);
$table = Carpenter::get('manufacturers signups');
```

I get the error `Undefined index: store` in

``` php
    protected function createStoreManager()
    {
        return new StoreManager($this->config['store'], $this->extensions['store']);
    }
```

When I inspect the state of the `Carpenter` object just before the error occurs, I can see that its `config` attribute is empty.

I think that I have valid configuration. I followed the instructions in [the documentation](http://carpenter.michaeljennings.im/getting-started) and exported settings using `php artisan config:publish michaeljennings/carpenter`.

Note that the error is not specific to the index `store`. When I manage to bypass the problem by hardcoding the correct configuration values in the package code, I get similar error for indices `session`, `paginator`, and `view`.

I use Laravel 4.2

**Comment by michaeljennings** [comment]
I've found the issue. 

I wasn't loading the config correctly in the laravel 4 service provider. It's been a while since I've worked with laravel 4 sorry.

I'm working on a fix now and that will be in v1.0.3.
