### ISSUE TITLE
Call to undefined method Illuminate\Pagination\Paginator::total()

### ISSUE THREAD

**Issue by PiotrJander** [michaeljennings/carpenter#7]
I get the following error message when rendering my table:

![error message](https://cloud.githubusercontent.com/assets/9830206/11937011/90e122e6-a809-11e5-99cf-021fdc147f80.png)

I'm using Carpenter v.1.0.4, Laravel 4.2. My store is set to 'eloquent'. 

I construct the table using the following code:

``` php
Carpenter::add('manufacturers signups', ManufacturerSignupsTable::class);
$table = Carpenter::get('manufacturers signups');
$table->model(User::class)->filter(function($q) {
    $q->where('company_id' , '!=', 'NULL');
});
```

My guess: incompatibility between Laravel 4 nd 5?

**Comment by michaeljennings** [comment]
Yeah they changed the paginator methods in between laravel 4 and 5. To fix that there is a laravel 4 specific store. In your config change the store to `laravel4` and that should fix the issue.
