### ISSUE TITLE
Pagination broken when using Laravel 4

### ISSUE THREAD

**Issue by PiotrJander** [michaeljennings/carpenter#9]
Adding this statement to the table declaration

``` php
$table->paginate(100);
```

yields this error message:
![zrzut ekranu 2016-01-18 o 10 05 13](https://cloud.githubusercontent.com/assets/9830206/12388510/36e63376-bdcb-11e5-8d4d-490a463a3872.png)

I use `laravel4` store and populate the table with the following code:

``` php
Carpenter::add('manufacturers signups', ManufacturerSignupsTable::class);
$table = Carpenter::get('manufacturers signups');
$table->model(User::class)->filter(function($q) {
    $q->where('company_id' , '!=', 'NULL');
});
```

**Comment by michaeljennings** [comment]
Sorry for the delay, had a couple of very busy days lately!

I've just tried running this on laravel 4.2.18 and it's working for me, can you tell me all of the config variables you have set, and which version of laravel you are using please?

**Comment by michaeljennings** [comment]
If you could let me know which version of carpenter you are using that would also be useful, thanks

**Comment by PiotrJander** [comment]
Here they are:
`carpenter v1.0.4`
`laravel  4.0.x-dev`
and carpenter config:

``` php
<?php

return array(

    'store' => array(

        /**
         * Set the store driver.
         *
         * Supported: eloquent, laravel4, illuminate, codeigniter, array.
         */
        'driver' => 'laravel4',

    ),

    'paginator' => array(

        /**
         * Set the pagination driver.
         *
         * Supported: illuminate, laravel4, native.
         */
        'driver' => 'native',

    ),

    'session' => array(

        /**
         * Set the session driver.
         *
         * Supported: illuminate, codeigniter, native.
         */
        'driver' => 'native',

        /**
         * Set the key to store session variables under.
         */
        'key' => 'michaeljennings.carpenter'

    ),

    'view' => array(

        /**
         * Set the view driver.
         *
         * Supported: illuminate, codeigniter, native.
         */
        'driver' => 'native',

        'views' => array(

            /**
             * Set the path to the default table template.
             */
            'template' => Config::get('app.base_path') . '/app/views/tables/table.php'
        )

    )
);
```

**Comment by michaeljennings** [comment]
Thanks for that. I've found the issue now, in laravel 4 you can't set the name of the paginator like you can in laravel 5. I've fixed that now and it will be added in the next point release.

**Comment by PiotrJander** [comment]
I updated the package, but pagination doesn't seem to be working
![](https://cloud.githubusercontent.com/assets/9830206/12675125/fd5e6d7c-c67f-11e5-8fdc-91af9d28bde2.png)
And it cannot work, as `Laravel 4.2`'s `Paginator` doesn't have the `all` method [(see API)](https://laravel.com/api/4.2/Illuminate/Pagination/Paginator.html)
